#!/bin/sh
#
# Usage: owswass <wav dir> <button gpio #>

# Export GPIO ($1), if needed and set direction ($2)
setup_io() {
	if [ ! -d "/sys/class/gpio/gpio$1" ]; then
		echo "Exporting /sys/class/gpio/gpio$1"
		echo $1 > /sys/class/gpio/export
		if [ $? -ne 0 ]; then
			echo "Failed to export GPIO" >&2
			exit
		fi

		if [ ! -d "/sys/class/gpio/gpio$1" ]; then
			echo "Unexpected error: gpio$1 is missing" >&2
			exit 1
		fi
	fi

	echo "$2" > "/sys/class/gpio/gpio$1/direction"

	# Return a value on button release
	if [ "$2" = "in" ]; then
		echo "falling" > "/sys/class/gpio/gpio$1/edge"
	fi
}

# Play random wav file from the directory specified in $1
play_rand_wav() {
	count=$(find "$1" -iname '*.wav' | wc -l)
	if [ ${count} -eq 0 ]; then
		echo "Error: Wav file directory does not contain files ending in .wav" >&2
		return
	fi

	val=$(tr -cd 0-9 < /dev/urandom | dd bs=4 count=1 2>/dev/null)
	val=$(expr "${val}" % "${count}")

	i=0
	for f in $(find "$1" -iname '*.wav'); do
		if [ $i -eq $val ]; then
			aplay "$f" > /dev/null
			return
		fi
		i=$(expr $i + 1)
	done
}

main() {
	if [ $# -ne 2 ]; then
		echo "Usage: owswaas <wav dir> <button gpio #>" >&2
		exit 1
	fi

	WAV_DIR="$1"
	if [ ! -d "${WAV_DIR}" ]; then 
		echo "No such directory: ${WAV_DIR}" >&2
		exit 1
	fi
	
	
	BTN="$2"
	if echo "${BTN}" | grep -Eq '[^0-9]'; then
		echo "Error: Button GPIO # must be numeric" >&2
		exit 1
	fi
	
	if [ ! -f /sys/class/gpio/export ]; then
		echo 'Error: GPIO Sysfs interface does not appear to be enabled.' >&2
		exit 1
	fi
	
	setup_io "${BTN}" "in"

	while [ 1 ]; do
		while [ "$(cat "/sys/class/gpio/gpio${BTN}/value")" -eq "1" ]; do
			usleep 15000
		done

		play_rand_wav "${WAV_DIR}"

		while [ "$(cat "/sys/class/gpio/gpio${BTN}/value")" -eq "0" ]; do
			usleep 15000
		done
	done
}	

main $@
